import './globals.css'
import { Inter } from 'next/font/google'
import SessionProviders from '../context/AuthProvider'
import Navbar from './components/Navbar'
import { CartProvider } from '@/context/CartContext'
const inter = Inter({ subsets: ['latin'] })
import { DataContextProvider } from '@/context/DataContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <SessionProviders>
      <DataContextProvider>
      <CartProvider>
        <Navbar />
        {/* <Slider /> */}
        <div>
        {children}
        </div>  
        </CartProvider>
        </DataContextProvider>
    </SessionProviders>
        </body>
    </html>
  )
}
